Categories = {
    "Animals": {
        1: "Dog",
        2: "Cat",
        3: "Lion",
        4: "Bear",
        5: "Horse",
        6: "Tiger",
        7: "Monkey",
        8: "Deer",
        9: "Goat",
        10: "Hippopotamus",
        11: "Cow",
        12: "Chicken",
        13: "Fish",
        14: "Dolphin",
        15: "Cheetah",
        16: "Kangaroo",
        17: "Pig",
        18: "Sharks",
        19: "Octopus",
        20: "Stingray",
        21: "Shrimp",
        22: "Starfish",
        23: "Lobsters",
        24: "Wolf",
        25: "Fox",
        26: "Rabbit",
        27: "Ostirich",
        28: "Camel",
        29: "Owl",
        30: "Elephant",
        31: "Snake",
        32: "Bat",
        33: "Beaver",
        34: "Bird",
        35: "Bobcat",
        36: "Blowfish",
        37: "Buffalo",
        38: "Frog",
        39: "Catfish",
        40: "Carp",
        41: "Chameleon",
        42: "Chipmunk",
        43: "Cougar",
        44: "Panther",
        45: "Crane",
        46: "Flamingo",
        47: "Emu",
        48: "Eel",
        49: "Whale",
        50: "Ferret",
        51: "Gorilla",
        52: "Donkey",
        53: "Dingo",
        54: "Crocodile",
        55: "Coyote",
        56: "Panther",
        57: "Hawk",
        58: "Chinchilla",
        59: "Gerbil",
        60: "Rat",
        61: "Giraffe",
        62: "Anteater",
        63: "Goose",
        64: "Honey Badger",
        65: "Hyena",
        66: "Hummingbird",
        67: "Iguana",
        68: "Jackal",
        69: "Jellyfish",
        70: "Leopard",
        71: "Lynx",
        72: "Komodo Dragon",
        73: "Macaw",
        74: "Penguin",
        75: "Meerkat",
        76: "Mink",
        77: "Mule",
        78: "Otter",
        79: "Seal",
        80: "Peacock",
        81: "Pheasant",
        82: "Pelican",
        83: "Platypus",
        84: "Puma",
        85: "Raccoon",
        86: "Quail",
        87: "Rhinoceros",
        88: "Lizard",
        89: "Scorpion",
        90: "Sea Lion",
        91: "Seahorse",
        92: "Sea Otter",
        93: "Sea Slug",
        94: "Sea Urchin",
        95: "Sea Turtle",
        96: "Turtle",
        97: "Sheep",
        98: "Skunk",
        99: "Sloth",
        100: "Sparrow",
        101: "Bull",
        102: "Squid",
        103: "Squirrel",
        104: "Orangatan",
        105: "Swan",
        106: "Turkey",
        107: "Vulture",
        108: "Crow",
        109: "Walrus",
        110: "Warthog",
        111: "Weasel",
        112: "Woodpecker",
        113: "Yak",
        114: "Zebra",
        115: "Wombat"
    },
    "Card Games": {
        1: "Yu-Gi-Oh",
        2: "Pokemon",
        3: "Force of Will",
        4: "Spite and Malice",
        5: "One Piece",
        6: "Poker",
        7: "Rummy",
        8: "Patience",
        9: "Canasta",
        10: "Cribbage",
        11: "Crazy Eights",
        12: "Palace",
        13: "War",
        14: "Klondike",
        15: "Baccarat",
        16: "Gong Zhu",
        17: "Big Two",
        18: "Free Cell",
        19: "Cheat",
        20: "Blitz",
        21: "Fan Turn",
        22: "GOPS",
        23: "Knock Out Whist",
        24: "Mao",
        25: "Palce",
        26: "President",
        27: "Ranter-Go-Round",
        28: "Speed",
        29: "Spoons",
        30: "Bridge",
        31: "Briscola",
        32: "Euchere",
        33: "German Whist",
        34: "Hearts", 
        35: "Spades",
        36: "Jass", 
        37: "Egyptian Ratscrew",
        38: "Ninety-Nine",
        39: "Rook",
        40: "Casino",
        41: "Eleusis",
        42: "Solitaire",
        43: "Big Two",
        44: "Texad Hold 'Em",
        45: "Skat",
        46: "Schnapsen",
        47: "Piquet",
        48: "Le Truc",
        49: "Bezique",
        50: "Blackjack",
        51: "Six Card Gold",
        52: "Kings Corner",
        53: "Euchere",
        54: "Thirty-One",
        55: "Old Maid",
        56: "Trash",
        57: "Red or Black",
        58: "Conquian",
        59: "Forty-Five",
        60: "Baseball Poker",
        61: "Spades with Joker",
        62: "Emperor",
        63: "Pepper",
        64: "Go Boom",
        65: "Cinch",
        66: "Boat House Run",
        67: "Fan Tan",
        69: "Michigan",
        70: "Bull Poker",
        71: "California Jack",
        72: "Quadruple War",
        73: "Shasta Sam",
        74: "Anaconda Poker",
        75: "Oh Pshaw",
        76: "Preference",
        77: "Snip Snap Snorem",
        78: "Page One",
        79: "Hollywood Eights",
        80: "Spar",
        81: "Cincinnati Poker",
        82: "Agram",
        83: "Spoil",
        84: "Let it Ride Stud Poker",
        85: "Play or Pay"
    },
    "Training": {
        1: "Jeff Adrien",
        2: "Arron Afflalo",
        3: "Maurice Ager",
        4: "Alexis Ajinca",
        5: "Cole Aldrich",
        6: "LaMarcus Aldridge",
        7: "Joe Alexander",
        8: "Ray Allen",
        9: "Malik Allen",
        10: "Tony Allen",
        11: "Al-Farouq Aminu",
        12: "Lou Amundson",
        13: "David Andersen",
        14: "Chris Andersen",
        15: "Ryan Anderson",
        16: "James Anderson",
        17:  "Carmelo Anthony", 
        18: "Joel Anthony",
        19:  "Gilbert Arenas",
        20: "Trevor Ariza",
        21: "Hilton Armstrong", 
        22: "Carlos Arroyo",
        23: "Darrell Arthur",
        24: "Omer Asik",
        25: "D.J. Augustin", 
        26: "Kelenna Azubuike",
        27: "Luke Babbitt",
        28: "Renaldo Balkman",
        29: "Marcus Banks",
        30: "Leandro Barbosa",
        31: "Jose Juan Barea",
        32: "Andrea Bargnani",
        33: "Matt Barnes",
        34: "Earl Barron",
        35: "Brandon Bass",
        36: "Tony Battle",
        37: "Shane Battier",
        38: "Nicolas Batum",
        39: "Jerryd Bayless",
        40: "Michael Beasley",
        41: "Rodrigue Beabois",
        42: "Marco Belinelli",
        43: "Charlie Bell",
        44: "Raja Bell",
        45: "Mike Bibby",
        46: "Andris Biedrins",
        47: "Chauncey Billups",
        48: "DeJuan Blair",
        49: "Steve Blake",
        50: "Andray Blatche",
        51: "Eric Bledsoe",
        52: "Keith Bogans",
        53: "Andrew Bogut",
        54: "Matt Bonner",
        55: "Trevor Booker",
        56: "Carlos Boozer",
        57: "Chris Bosh",
        58: "Earl Boykins",
        59: "Craig Brackins",
        60: "Avery Bradley",
        61: "Elton Brand",
        62: "Ronnie Brewer",
        63: "Corey Brewer",
        64: "Jon Brockman",
        65: "Aaron  Brooks",
        66: "Derrick Brown",
        67: "Kwame Brown",
        68: "Shannon Brown",
        69: "Kobe Bryant",
        70: "Chase Budinger",
        71: "Rasual Butler",
        72: "Caron Butler",
        73: "Will Bynum",
        74: "Andrew Bynum"

    }
}