vocablist = (["wox", "raw", "out", "die", "apt", "yaw", "jab", "nis", "rew", "tap", "pip", "hep", "fob", "mum", 
             "lat", "bub", "spa", "was", "rib", "sap", "tin", "mac", "fen", "dog", "cat", "rat", "that", "with", "this", "from", "have", "were", 
             "they", "will", "been", "more", "such", "when", "time", "than", "some", "what", "only", "into", "also", "them", "then", "said", "made", "your", "most", "over", "each", "year", 
             "work", "same", "many", "upon", "must", "well", "very", "used", "both", "life", "good", "york", "long", "high", "part", "like", "even", "make", "case", "much", "area", "fact", 
             "line", "come", "four", "thus", "land", "give", "bill", "hand", "held", "name", "left", "best", "five", "find", 
             "type", "full", "rule", "true", "took", "seen", "ever", "went", "cent", 
             "paid", "room", "view", "note", "side", "care", "book", "next", "body", "done", "head", "feet", "plan", "once", "which", "their", "other", "there", "would", "these", 
             "about", "state", "under", "first", "after", "shall", "could", "where", "years", "those", "being", "court", "three", "water", "order", "great", "while", "right", "found", 
             "power", "world", "given", "since", "every", "house", "place", "total", "large", "small", "might", "point", "board", "still", "study", "value", "think", "until", "group", 
             "never", "means", "cases", "among", "above", "table", "local", "again", "taken", "based", "often", "women", "times",
             "field", "level", "white", "human", "known", "south", "light", "using", 
             "early", "least", "north", "world", "class", "later", "layer", "labor", "money", 
             "going", "shown", "third", "party", "young", "sloth", "works", "close", "clear", "lines", "miles", "parts", "space", "thing", "night", "day", "rules", "boxes", "black", 
             "white", "basis", "stock", "issue", "plant", "costs", "model", "hours", "Seemly", "Sumoom", 
             "Dorado", "Durity", "Ending", "Muting", "Papess", "Ceased", "Floury", "Repkie", "Agible", "Routed", "Chatty", 
             "Became", "Annual", "Humble", "Flashy", "Absurd", "Select", "Atomic", "Potash", "Uneven", "Coined", "Parcel", "Marrow", "Beyond", "Loving", "Limper", "Tissue", "Dazzle", 
             "Peachy", "Scrape", "Harbor", "Thrown", "Saturn", "Uproar", "Mormon", 
             "Bullet", "Nibble", "Attach", "Drawer", "Ponder", "Striped", "Iranian", 
             "Colored", "Scarred", "Selvage", 
             "Conduct", "Playful", "Enhance", "Petting", 
             "Miserly", "Hashing", "Lowland", "Groomed", "Regress", "Founder", "Drastic", "Sundial", "Jarring", "Pinhold", "Lapping", "Adipous", "Mangoes", "Adverse", "Sectant", 
             "Winning", "Logging", "Joisted", "Rhombus", "Fancied", "Uncloak", "Unblind", "Enscale", "Dismant", "Refound", "Tadpole", "English", "Dicebox", "Convict", "Sharded", "Provide", 
             "Glosser", "Rhymery", "national", "business", "research", "children", "interest", "services", "property", "question", "required", "possible",
             "provided", "evidence", "although", "district", "increase", "economic", 
             "analysis", "received", "material", "position", "problems", "building", "industry", "contract", 
             "congress", "products", "together", "students", "programs", "specific", "addition", "practice", "standard", "personal", 
             "training", "division", "complete", "reported", "proposed", "military", "chairman", "language", "security", "obtained", "pressure", 
             "decision", "director", "probably", "purposes", "judgement", "function", "included", "activity", "original", "physical", "officers", 
             "patients", "involved", "produced", "solution", "response", "provides", "approach", "hospital", "anything", "movement", "planning", "expected", "benefits", 
             "consider", "electric", "capacity", "railroad", "referred", "directly", 
             "includes", "followed", "exchange", "entitled", "existing", "continue", "prepared", "southern", "northern", 
             "behavior", "computer", "transfer", "commerce", "agencies", "approved", "observed", "teachers", 
             "actually", "chemical", "relative", "previous", "separate", "sections", "learning", "expenses", "employed", "attorney"
            "apple", "banana", "grapes", "pear", "orange", "corn", "rice", "peas", "bread", "milk", "eggs", 
            "cheese", "beans", "pasta", "soup", "salad", "cake", "pie", "fish", "meat","Celtics", "Heat", "Mets", 
            "Cardinals", "Steelers", "Raiders", "Broncos", "Bears", "Knicks", "Falcons", "Eagles", "pineapple", 
            "strawberry", "raspberry", "avocado", "mango", "pomegranate", "asparagus", "artichoke", "spinach", 
            "kale", "feta", "gnocchi", "paella", "tiramisu", "croissant", "pancake", "waffle", "muffin", "scone", 
            "bagel", "Seahawks", "Cavaliers", "Cubs", "Astros", "Hornets", "Wizards", "Suns", "Raptors", "Bucks", 
            "Kings", "Nuggets", "Twins", "Rays", "Padres", "Tigers", "Ravens", "Bills", "Chiefs", "Dolphins", "Saints",
            "kumquat", "durian", "ackee", "salak", "rambutan", "longan", "sapodilla", "cherimoya", "tamarillo", 
            "jabuticaba", "huitlacoche", "natto", "umeboshi", "sucuk", "nduja", "gravlax", "bobotie", "cassoulet", 
            "fufu", "moussaka", "Avalanche", "Bluejackets", "Trailblazers", "Jets", "Canucks", "Predators", "Coyotes", 
            "Panthers", "Wild", "Islanders", "Oilers", "Sabres", "Devils", "Maple Leafs", "Flyers", "Sharks", "Lightning", 
            "Flames", "Ducks", "Senators", "red", "blue", 
            "green", "white", "black", "brown", "yellow", "orange",
            "purple", "gold", "gray", "teal", "indigo", "silver", "violet", "pink",
            "beige", "indigo", "crimson", "cyan", "olive", "apple", "oranges", "banana", "pear", "watermelon", "canteloupe",
            "grapes", "tomato", "dragon fruit", "papaya", "pineapple", "green apple", 
            "peaches", "plums", "guava", "durian", "jack fruit", "soursop", "lychee berry",
            "blueberries", "blackberries", "cherry", "crab apples", "kiwi", 
        "cotton candy grapes", "strawberries", "mango", "dates", "coconut", "Yu-Gi-Oh", "Pokemon", "Magic the Gathering", 
        "Force of Will", "One Piece TCG", "Spoil", "Poker", "Rummy", "Patience",
         "Gin Rummy", "Cribbage", "Crazy Eights", "War", "Egyptian Ratscrew",
        "Canasta", "Spite and Malice", "Klondike", "Baccarat", "Gong Zhu", 
        "Big Two", "Free Cell", "Cheat", "Blitz", "Fan Turn", "GOPS", 
        "Knock Out Whist", "Mao", "Palace", "President", "President", 
        "Ranter-Go-Round", "speed", "Spoons", "Bridge", "Briscola", "Euchere",
        "German Whist", "Hearts", "Spades", "Jass", "Ninety-Nine", "Rook", 
        "Casino", "Eleusis", "Solitaire", "Big Two", "Texas Hold 'Em", "Skat", 
        "Schnapsen", "Piquet", "Le Truc", "Bezique", "Blackjack", "War", 
        "Six Card Golf", "Kings Corner", "Euchre", "Thirty-One", "Old Maid",
        "Trash", "Red or Black", "Conquian", "Forty-Fve", "Baseball Poker",
        "Spades With Jokers", "Emperor", "Pepper", "Go Boom", "Cinch", 
        "Boat House Run", "Fan Tan", "Michigan", "Bull Poker", "california Jack"
        , "Quadruple War", "Shasta Sam", "Anaconda Poker", "Baccarat", 
        "Oh Pshaw", "Preference", "Snip Snap Snorem", "Hold 'Em", "Page One",
        "Hollywood Eights", "Spar", "Page One", "Cincinnati Poker", "Agram",
        "Spoil", "Let it Ride Stud Poker", "Play or Pay", "the Game of Life", "Clue", "Candy Land", "Monopoly",
        "Scrabble", "Battleship", "Risk", "Stratego", "Axis & Allies", 
        "Backgammon", "Checkers", "Chinese Checkers", "Blockus", "Agricola",
        "Connect Four", "Twister", "Operation", "Don't Break the Ice", 
        "hungry hungry Hippos", "Boogle", "Mouse Trap", "Jenga", "Mastermind",
        "Qwirkle", "Uno", "Cranium", "Dominoes", "Chutes and Ladders", 
        "Carcassonne", "Traffic Jam", "Trouble", "Ticket to Ride", "Sorry", 
        "Yahtzee", "Pictionary", "Apples to Appples", "Scattergories",
        "Catchphrase", "Taboo", "Speak Out", "Password", "Mad Lab", 
        "Adult Board Games", "Trivial Pursuit", "Sequence", "Catan", "Domino",
        "Cribbage", "Card Against Humanity", "Azul", "Jeff Adrien", 
        "Arron Afflalo",
         "Maurice Ager",
          "Alexis Ajinca", 
          "Cole Aldrich",
           "LaMarcus Aldridge",
    "Joe Alexander",
     "Ray Allen",
      "Malik Allen", "Tony Allen", "Al-Farouq Aminu", "Lou Amundson", "David Andersen", "Chris Andersen", "Ryan Anderson",
     "James Anderson", "Carmelo Anthony", "Joel Anthony", "Gilbert Arenas", "Trevor Ariza", "Hilton Armstrong", "Carlos Arroyo", "Darrell Arthur", "Omer Asik",
    "D.J. Augustin", "Kelenna Azubuike", "Luke Babbitt", "Renaldo Balkman", "Marcus Banks", "Leandro Barbosa", "Jose Juan Barea", "Andrea Bargnani", 
    "Matt Barnes", "Earl Barron", "Brandon Bass", "Tony Battle", "Shane Battier", "Nicolas Batum", "Jerry Bayless", "Michael Beasley", "Rodrigue Beabois",
    "Marco Belinelli", "Charlie Bell", "Raja Bell", "Mike Bibby", "Andris Biedrins", "Chauncey Billups", "DeJuan Blair", "Steve Blake", "Andray Blatche",
    "Eric Bledsoe", "Keith Bogans", "Andrew Bogut", "Matt Bonner", "Trevor Booker", "Carlos Boozer", "Chris Bosh", "Earl Boykins", "Craig Brackins", "Avery Bradley",
    "Elton Brand", "Ronnie Brewer", "Corey Brewer", "Jon Brockman", "Aaron  Brooks", "Derrick Brown", "Kwame Brown", "Shannon Brown", "Kobe Bryant", "Chase Budinger",
    "Rasual Butler", "Caron Butler", "Will Bynum", "Andrew Bynum"])
